---
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
  - name: Gathering Facts
    setup:
  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
  - name: Run dist-upgrade
    apt:
      upgrade: dist
  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
  - name: Check if a reboot is required
    shell: "[ -f /var/run/reboot-required ]"
    failed_when: False
    register: reboot_required
    changed_when: reboot_required.rc == 0
    notify: reboot
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  - name: Install Docker-CE and related packages
    apt:
      name: ['apt-transport-https','ca-certificates','curl','gnupg-agent','software-properties-common','docker-ce','docker-ce-cli','containerd.io']
      state: present
      update_cache: yes

  handlers:
  - name: Reboot
    reboot:
