-  hosts: HiGHmed
   become: true
   gather_facts: false
   pre_tasks:
   -  name: Install python2 for Ansible
      raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
      register: output
      changed_when: output.stdout != ""
   -  name: Gathering Facts
      setup: null
   tasks:
   -  name: Run dist-upgrade
      apt:
         upgrade: dist
         update_cache: true
   -  name: Install azure kernel
      apt:
         name: linux-azure
         state: present
   -  name: Remove dependencies that are no longer required
      apt:
         autoremove: true
   -  name: Check if a reboot is required
      shell: '[ -f /var/run/reboot-required ]'
      failed_when: false
      register: reboot_required
      changed_when: reboot_required.rc == 0
      notify: Reboot
   -  name: Add Docker GPG key
      apt_key:
         url: https://download.docker.com/linux/ubuntu/gpg
         state: present
   -  name: Verify Docker GPG key
      apt_key:
         id: 0EBFCD88
         state: present
   -  name: Add Docker APT repository
      apt_repository:
         repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
         state: present
         update_cache: true
   -  name: Install Docker-CE and related packages
      apt:
         name:
         - apt-transport-https
         - ca-certificates
         - curl
         - gnupg-agent
         - software-properties-common
         - docker-ce
         - docker-ce-cli
         - containerd.io
         state: present
         update_cache: true
   -  name: update /etc/hosts file
      blockinfile:
         path: /etc/hosts
         block: |
            {{ item.ip }} {{ item.name }}
         marker: '# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}'
      with_items:
      -  name: registry
         ip: 10.42.0.1
      -  name: ttp
         ip: 10.42.0.10
      -  name: medic1
         ip: 10.42.0.11
      -  name: medic2
         ip: 10.42.0.12
      -  name: medic3
         ip: 10.42.0.13
   handlers:
   -  name: Reboot
      reboot: null